SELECT ?airport ?iata ?icao ?airportLabel ?patronage ?point_in_time WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  VALUES ?airport_classes { wd:Q1248784 wd:Q62447 wd:Q644371 }
  ?airport wdt:P31 ?airport_classes.
  ?airport p:P3872 ?patronage_statement.
  ?patronage_statement ps:P3872 ?patronage.
  ?patronage_statement pq:P585 ?point_in_time.
  ?airport p:P238 ?iata_statement. 
  ?iata_statement ps:P238 ?iata.
  ?airport p:P239 ?icao_statement.
  ?icao_statement ps:P239 ?icao.
  FILTER ( ?iata IN ( "AUX", "MUC", "LAX" ) )
  FILTER ( YEAR(?point_in_time) < 2018 && YEAR(?point_in_time) > 2010)
}
